# Generated by Django 4.2.28 on 2026-02-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursementrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_SUPER_ADMIN_REVIEW', 'Pending Super Admin Review'), ('PENDING_VAULT_MANAGER_APPROVAL', 'Pending Vault Manager Approval'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING_SUPER_ADMIN_REVIEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='disbursementrequest',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.vault'),
        ),
    ]
