# Generated by Django 4.2.28 on 2026-02-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_disbursementrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementrequest',
            name='requested_payout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
